spring:
  profiles: dev
  application:
    name: bookcha
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  output:
    ansi:
      enabled: always
  flyway:
    enabled: false
  cloud:
    kubernetes:
      enabled: false
    discovery:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true